#137085767 Export workouts to JSON
andela/wger_asgards pull request #6
Opened 2017-01-19 14:21 UTC by andela-bmwenda

#### What does this PR do?
Adds functionality to export workouts in a JSON file

#### Description of Task to be completed?
- Add a button that the user clicks to download workouts
- Enable the user to download their workouts in their local system

#### How should this be manually tested?
- Run python manage.py test

#### What are the relevant pivotal tracker stories?
#137085767

2017-01-19 18:24 UTC, andela-osule commented on wger/manager/views/workout.py
> +from django.http import HttpResponse
We can combine imported classes from `django.http` here.

2017-01-19 18:30 UTC, andela-bmwenda commented on wger/manager/views/workout.py
> +from django.http import HttpResponse
Okay, noted

2017-01-19 18:31 UTC, osule requested changes

2017-01-19 18:31 UTC, andela-osule commented on wger/manager/views/workout.py
> +# from django.manager.serializers import WorkoutExportSerializer
Shall we be needing this commented out import?

2017-01-19 18:31 UTC, andela-osule commented on wger/manager/views/workout.py
> +from import_export import resources
This looks to be unused. What the intent?

2017-01-19 18:34 UTC, andela-bmwenda commented on wger/manager/views/workout.py
> +from import_export import resources
It has been used the class that gets the items in the workout model as Json. Here: `class ExportWorkoutsResource(resources.ModelResource)`

2017-01-19 18:35 UTC, andela-bmwenda commented on wger/manager/views/workout.py
> +# from django.manager.serializers import WorkoutExportSerializer
No, I'll get rid of that

2017-01-23 09:22 UTC, osule approved these changes
LGTM

2017-01-23 09:22 UTC, merged